### ISSUE TITLE
set dvar "load_iw3mvm" to true to auto-load iw3mvm

### ISSUE THREAD

**Issue by xoxor4d** [kruumy/iw3xo-one-click-installer#1]
set dvar `load_iw3mvm` to `1` via startup parameters to load `iw3mvm.dll` from `iw3xo\bin` 🙌

**Comment by kruumy** [comment]
Has not been working for me for awhile, used to work but the dvar is not even getting defined anymore 
![image](https://user-images.githubusercontent.com/48849543/162636898-d9e20e3e-5aab-4da8-98ec-0aca1c9624d9.png)
The dll is renamed and everything. I just have been using a different injector with the dll for awhile now since the normal method does not work.

**Comment by xoxor4d** [comment]
Ah yes sorry for my in incompetence 😜
I’ve mistakenly disabled the registration of this dvar whilst disabling the mvm module. I‘ll fix that within the next release
